export enum Semantics {
    DEFAULT = "DEFAULT",
    QUERY = "QUERY",
    RESPONSE = "RESPONSE",
}

export enum Status {
    OK = "OK",
    FAILURE = "FAILURE",
    UNKNOWN = "UNKNOWN",
    INVALID_ARGUMENT = "INVALID_ARGUMENT",
    DEADLINE_EXCEEDED = "DEADLINE_EXCEEDED",
    ALREADY_EXISTS = "ALREADY_EXISTS",
    PERMISSION_DENIED = "PERMISSION_DENIED",
    RESOURCE_EXHAUSTED = "RESOURCE_EXHAUSTED",
    FAILED_PRECONDITION = "FAILED_PRECONDITION",
    ABORTED = "ABORTED",
    OUT_OF_RANGE = "OUT_OF_RANGE",
    UNIMPLEMENTED = "UNIMPLEMENTED",
    INTERNAL = "INTERNAL",
    UNAVAILABLE = "UNAVAILABLE",
    DATA_LOSS = "DATA_LOSS",
    UNAUTHENTICATED = "UNAUTHENTICATED",

    // HTTP Codes - ---------------------------------------------------------------
    BAD_REQUEST = "BAD_REQUEST",
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    NOT_FOUND = "NOT_FOUND",
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED",
    CONFLICT = "CONFLICT",
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE",
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
    INSUFFICIENT_STORAGE = "INSUFFICIENT_STORAGE",

    UNPARSEABLE_RESPONSE = "UNPARSEABLE_RESPONSE",

    // General Failures - ----------------------------------------------------------
    DISABLED_CUSTOMER = "DISABLED_CUSTOMER",
    INVALID_CUSTOMER_ID = "INVALID_CUSTOMER_ID",
    DISABLED_CORPUS = "DISABLED_CORPUS",
    INVALID_CORPUS_ID = "INVALID_CORPUS_ID",
    DISABLED_API_KEY = "DISABLED_API_KEY",
    EXPIRED_API_KEY = "EXPIRED_API_KEY",
    INVALID_API_KEY = "INVALID_API_KEY",
    CMK_INACCESSIBLE = "CMK_INACCESSIBLE",

    // Serving Query - ------------------------------------------------------------
    QRY__DISABLED_CORPUS = "QRY__DISABLED_CORPUS",
    QRY__DOCUMENT_DB_FAILURE = "QRY__DOCUMENT_DB_FAILURE",
    QRY__ENCODER_FAILURE = "QRY__ENCODER_FAILURE",
    QRY__INTERRUPTED = "QRY__INTERRUPTED",
    QRY__INVALID_CORPUS = "QRY__INVALID_CORPUS",
    QRY__INVALID_START = "QRY__INVALID_START",
    QRY__INVALID_NUM_RESULTS = "QRY__INVALID_NUM_RESULTS",
    QRY__MISSING_QUERY = "QRY__MISSING_QUERY",
    QRY__MISSING_CORPUS = "QRY__MISSING_CORPUS",
    QRY__TIMEOUT = "QRY__TIMEOUT",
    QRY__TOO_MANY_CORPORA = "QRY__TOO_MANY_CORPORA",
    QRY__TOO_MANY_QUERIES = "QRY__TOO_MANY_QUERIES",
    QRY__VECTOR_INDEX_FAILURE = "QRY__VECTOR_INDEX_FAILURE",
    QRY__INVALID_DIMENSION = "QRY__INVALID_DIMENSION",
    QRY__INVALID_CLIENTKEY = "QRY__INVALID_CLIENTKEY",
    QRY__DECRYPTION_FAILURE = "QRY__DECRYPTION_FAILURE",
    QRY__INVALID_RERANKER = "QRY__INVALID_RERANKER",
    QRY__PARTIAL_RERANK = "QRY__PARTIAL_RERANK",
    QRY__RERANK_FAILURE = "QRY__RERANK_FAILURE",
    QRY__TOO_MANY_RESULT_ROWS = "QRY__TOO_MANY_RESULT_ROWS",

    QRY__SMRY__INVALID_SUMMARIZER_PROMPT = "QRY__SMRY__INVALID_SUMMARIZER_PROMPT",
    QRY__SMRY__INVALID_SUMMARY_LANG = "QRY__SMRY__INVALID_SUMMARY_LANG",
    QRY__SMRY__UNSUPPORTED_SUMMARY_LANG = "QRY__SMRY__UNSUPPORTED_SUMMARY_LANG",
    QRY__SMRY__PARTIAL_SUMMARY = "QRY__SMRY__PARTIAL_SUMMARY",
    QRY__SMRY__NO_QUERY_RESULTS = "QRY__SMRY__NO_QUERY_RESULTS",
    QRY__GEN__NO_QUERY_RESULTS = "QRY__GEN__NO_QUERY_RESULTS",
    QRY__GEN__UNPARSEABLE_MODEL_PARAMS = "QRY__GEN__UNPARSEABLE_MODEL_PARAMS",




    // Connection specs - ---------------------------------------------------------
    CX_SPECS__INVALID_JSON = "CX_SPECS__INVALID_JSON",
    CX_SPECS__UNREGISTERED_TYPE = "CX_SPECS__UNREGISTERED_TYPE",
    CX_SPECS__MISSING_SPEC = "CX_SPECS__MISSING_SPEC",
    CX_SPECS__MISSING_TYPE = "CX_SPECS__MISSING_TYPE",
    CX_SPECS__UNPARSEABLE_SPEC = "CX_SPECS__UNPARSEABLE_SPEC",

    // Admin Service - ------------------------------------------------------------
    ADM__INVALID_CUSTOMER_ID = "ADM__INVALID_CUSTOMER_ID",
    ADM__INVALID_CORPUS_ID = "ADM__INVALID_CORPUS_ID",
    ADM__INVALID_ENCODER_ID = "ADM__INVALID_ENCODER_ID",
    ADM__INVALID_ROLE_ID = "ADM__INVALID_ROLE_ID",
    ADM__ROLE_ALREADY_EXISTS = "ADM__ROLE_ALREADY_EXISTS",
    ADM__ONLY_ONE_OWNER_SUPPORTED = "ADM__ONLY_ONE_OWNER_SUPPORTED",
    ADM__INVALID_PERMISSION = "ADM__INVALID_PERMISSION",
    ADM__ROLECREATION_FAILURE = "ADM__ROLECREATION_FAILURE",
    ADM__USER_EMAIL_NOT_AVAIALBLE = "ADM__USER_EMAIL_NOT_AVAIALBLE",
    ADM__USERNAME_NOT_AVAILABLE = "ADM__USERNAME_NOT_AVAILABLE",

    ADM__SIGNUP_MISSING_NAME = "ADM__SIGNUP_MISSING_NAME",
    ADM__SIGNUP_MISSING_ORG = "ADM__SIGNUP_MISSING_ORG",
    ADM__SIGNUP_MISSING_EMAIL = "ADM__SIGNUP_MISSING_EMAIL",
    ADM__SIGNUP_MISSING_PAYMENT = "ADM__SIGNUP_MISSING_PAYMENT",
    ADM__SIGNUP_MISSING_PLAN = "ADM__SIGNUP_MISSING_PLAN",
    ADM__SIGNUP_MISSING_PASSWORD = "ADM__SIGNUP_MISSING_PASSWORD",

    ADM__SIGNUP_INVALID_NAME = "ADM__SIGNUP_INVALID_NAME",
    ADM__SIGNUP_INVALID_ORG = "ADM__SIGNUP_INVALID_ORG",
    ADM__SIGNUP_INVALID_EMAIL = "ADM__SIGNUP_INVALID_EMAIL",
    ADM__SIGNUP_INVALID_PAYMENT = "ADM__SIGNUP_INVALID_PAYMENT",
    ADM__SIGNUP_INVALID_PLAN = "ADM__SIGNUP_INVALID_PLAN",
    ADM__SIGNUP_INVALID_PASSWORD = "ADM__SIGNUP_INVALID_PASSWORD",
    ADM__SIGNUP_INVALID_ACCOUNT_ALIAS = "ADM__SIGNUP_INVALID_ACCOUNT_ALIAS",
    ADM__SIGNUP_INVALID_EMAIL_VALIDATION_CODE = "ADM__SIGNUP_INVALID_EMAIL_VALIDATION_CODE",
    ADM__SIGNUP_MISSING_COUNTRY_CODE = "ADM__SIGNUP_MISSING_COUNTRY_CODE",
    ADM__SIGNUP_ROOT_EMAIL_NOT_AVAILABLE = "ADM__SIGNUP_ROOT_EMAIL_NOT_AVAILABLE",

    ADM__CUST_MARK_DELETE_FAILED = "ADM__CUST_MARK_DELETE_FAILED",
    ADM__CUST_FAISS_DEALLOC_FAILED = "ADM__CUST_FAISS_DEALLOC_FAILED",
    ADM__CUST_ALREADY_ACTIVE = "ADM__CUST_ALREADY_ACTIVE",
    ADM__CUST_REACTIVATE_FAILED = "ADM__CUST_REACTIVATE_FAILED",
    ADM__CUST_ENABLEMENT_FAILED = "ADM__CUST_ENABLEMENT_FAILED",

    ADM__CORPUS_LIMIT_REACHED = "ADM__CORPUS_LIMIT_REACHED",

    ADM__STRIPE_CARD_DECLINED = "ADM__STRIPE_CARD_DECLINED",
    ADM__STRIPE_PROCESSING_ERROR = "ADM__STRIPE_PROCESSING_ERROR",

    ADM__EMAIL_VALIDATION_REQUEST_NOT_FOUND = "ADM__EMAIL_VALIDATION_REQUEST_NOT_FOUND",
    ADM__EMAIL_NOT_VALIDATED = "ADM__EMAIL_NOT_VALIDATED",

    // Schema Services - ----------------------------------------------------------
    SCM__MISCONFIGURED_CONNECTION = "SCM__MISCONFIGURED_CONNECTION",

    // Druid Errors
    DRUID_READ_FAILURE = "DRUID_READ_FAILURE",
    DRUID_INVALID_DATA = "DRUID_INVALID_DATA",
    DRUID_NO_DATA = "DRUID_NO_DATA",

    // StatDB Errors
    STATS_DB_READ_FAILURE = "STATS_DB_READ_FAILURE",

    // Vector Database - ----------------------------------------------------------

    VDB__TEXT_READ_FAILURE = "VDB__TEXT_READ_FAILURE",

    // Index rebuild codes - -----------------------------------------------------
    REBUILD__LOW_RECALL = "REBUILD__LOW_RECALL",
    REBUILD__INDEX_UPLOAD_FAILURE = "REBUILD__INDEX_UPLOAD_FAILURE",
    REBUILD__UPDATE_JOURNAL_FAILURE = "REBUILD__UPDATE_JOURNAL_FAILURE",
    REBUILD__UPDATE_FAISSPARAMS_FAILURE = "REBUILD__UPDATE_FAISSPARAMS_FAILURE",
    REBUILD__NO_DATA = "REBUILD__NO_DATA",
    REBUILD__EVALUATION = "REBUILD__EVALUATION",

    // Indexing - -----------------------------------------------------------------
    IDX__TRANSIENT_PARTIAL_DELETION_FAILURE = "IDX__TRANSIENT_PARTIAL_DELETION_FAILURE",
    IDX__PERMANENT_PARTIAL_DELETION_FAILURE = "IDX__PERMANENT_PARTIAL_DELETION_FAILURE",

    // Calibration
    CALB__INVALID_JSON = "CALB__INVALID_JSON",
    CALB__INVALID_SPEC = "CALB__INVALID_SPEC",
    CALB__UNREGISTERED_TYPE = "CALB__UNREGISTERED_TYPE",
    CALB__MISSING_SPEC = "CALB__MISSING_SPEC",
    CALB__MISSING_TYPE = "CALB__MISSING_TYPE",
    CALB__UNPARSABLE_SPEC = "CALB__UNPARSABLE_SPEC",
}