<?php
/**
 * Language
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vectara REST API v2
 *
 * Vectara provides an end-to-end platform for creating GenAI products using  a simple to use API.  You can [sign up for an account](https://console.vectara.com/signup) and  then view several [API Recipes](https://docs.vectara.com/docs/api-recipes) with example queries  and parameter values.  The Vectara API Playground lets you experiment with REST endpoints from  your browser. Select an endpoint to view its definition, including the  required or optional headers, body, responses, and sample commands. On the  right side of each endpoint page, like [Get Corpus](/docs/rest-api/get-corpus), you manually  enter your API Key or OAuth Bearer Token, `customer_id`, and then any  required body parameters like the `corpusID` before sending the API  request.  :::note  Vectara supports two primary methods of authentication: API keys and OAuth  2.0, which are applicable to all endpoints. Query API Keys are used for  read-only querying operations, while Index API Keys provide read and write  access. The OAuth 2.0 operations authenticate with a Bearer Token via the  OAuth 2.0 client credentials grant. Review the [**OAuth 2.0 section**](https://docs.vectara.com/docs/learn/authentication/oauth-2) about  how to generate the token.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: feedback@vectara.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\VectaraModel;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Language Class Doc Comment
 *
 * @category Class
 * @description Languages that the Vectara platform supports.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Language
{
    /**
     * Possible values of this enum
     */
    public const AUTO = 'auto';

    public const ENG = 'eng';

    public const DEU = 'deu';

    public const FRA = 'fra';

    public const ZHO = 'zho';

    public const KOR = 'kor';

    public const ARA = 'ara';

    public const RUS = 'rus';

    public const THA = 'tha';

    public const NLD = 'nld';

    public const ITA = 'ita';

    public const POR = 'por';

    public const SPA = 'spa';

    public const JPN = 'jpn';

    public const POL = 'pol';

    public const TUR = 'tur';

    public const VIE = 'vie';

    public const IND = 'ind';

    public const CES = 'ces';

    public const UKR = 'ukr';

    public const ELL = 'ell';

    public const HEB = 'heb';

    public const FAS = 'fas';

    public const HIN = 'hin';

    public const URD = 'urd';

    public const SWE = 'swe';

    public const BEN = 'ben';

    public const MSA = 'msa';

    public const RON = 'ron';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AUTO,
            self::ENG,
            self::DEU,
            self::FRA,
            self::ZHO,
            self::KOR,
            self::ARA,
            self::RUS,
            self::THA,
            self::NLD,
            self::ITA,
            self::POR,
            self::SPA,
            self::JPN,
            self::POL,
            self::TUR,
            self::VIE,
            self::IND,
            self::CES,
            self::UKR,
            self::ELL,
            self::HEB,
            self::FAS,
            self::HIN,
            self::URD,
            self::SWE,
            self::BEN,
            self::MSA,
            self::RON
        ];
    }
}


