/**
 * Vectara REST API v2
 * Vectara provides an end-to-end platform for creating GenAI products using  a simple to use API.  You can [sign up for an account](https://console.vectara.com/signup) and  then view several [API Recipes](https://docs.vectara.com/docs/api-recipes) with example queries  and parameter values.  The Vectara API Playground lets you experiment with REST endpoints from  your browser. Select an endpoint to view its definition, including the  required or optional headers, body, responses, and sample commands. On the  right side of each endpoint page, like [Get Corpus](/docs/rest-api/get-corpus), you manually  enter your API Key or OAuth Bearer Token, `customer_id`, and then any  required body parameters like the `corpusID` before sending the API  request.  :::note  Vectara supports two primary methods of authentication: API keys and OAuth  2.0, which are applicable to all endpoints. Query API Keys are used for  read-only querying operations, while Index API Keys provide read and write  access. The OAuth 2.0 operations authenticate with a Bearer Token via the  OAuth 2.0 client credentials grant. Review the [**OAuth 2.0 section**](https://docs.vectara.com/docs/learn/authentication/oauth-2) about  how to generate the token. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: feedback@vectara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IndividualSearchResult } from './individualSearchResult';
import { Language } from './language';

/**
* Full response to a chat question when the result is not streamed.
*/
export class ChatFullResponse {
    /**
    * If the chat response was stored, the ID of the chat.
    */
    'chatId'?: string;
    /**
    * If the chat response was stored, the ID of the turn.
    */
    'turnId'?: string;
    /**
    * The message from the chat model for the chat message.
    */
    'answer'?: string;
    'responseLanguage'?: Language;
    /**
    * The ranked search results that the chat model used.
    */
    'searchResults'?: Array<IndividualSearchResult>;
    /**
    * The probability that the summary is factually consistent with the results. 
    */
    'factualConsistencyScore'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "chatId",
            "baseName": "chat_id",
            "type": "string"
        },
        {
            "name": "turnId",
            "baseName": "turn_id",
            "type": "string"
        },
        {
            "name": "answer",
            "baseName": "answer",
            "type": "string"
        },
        {
            "name": "responseLanguage",
            "baseName": "response_language",
            "type": "Language"
        },
        {
            "name": "searchResults",
            "baseName": "search_results",
            "type": "Array<IndividualSearchResult>"
        },
        {
            "name": "factualConsistencyScore",
            "baseName": "factual_consistency_score",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ChatFullResponse.attributeTypeMap;
    }
}

export namespace ChatFullResponse {
}
